[package]
name = "ods2cascade"
description = "A command line tool to assist with migration from OpenDNSSEC to Cascade"
version = "0.1.0-alpha1"
homepage = "https://nlnetlabs.nl/projects/casaade"
documentation = "https://cascade.docs.nlnetlabs.nl"
edition = "2024"
license = "BSD-3-Clause"
exclude = [".github", ".gitignore"]
readme = "README.md"
rust-version = "1.88"

[dependencies]
anyhow            = "1.0.100"
atoi              = "2.0.0"
cascade-cfg       = { git = "https://github.com/NLnetLabs/cascade", package = "cascade-cfg" }
cascade-policy    = { git = "https://github.com/NLnetLabs/cascade", package = "cascade-policy-file" }
domain            = { git = "https://github.com/NLnetLabs/domain", branch = "main" } # Use the same domain as cascade
file-owner        = "0.1.2"
fs-err            = "3.2.2"
indoc             = "2.0.7"
cascade-hsm-bridge-cfg = { git = "https://github.com/NLnetLabs/cascade-hsm-bridge", version = "0.1.0-alpha" }
pretty_assertions = "1.4.1"
quick-xml         = { version = "0.38.4", features = ["serialize"] }
ron               = "0.12.0"
sanitize-filename = "0.6.0"
serde             = { version = "1.0.228", features = ["derive"] }
sqlx              = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "mysql"] }
tokio             = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
toml              = "0.9.11"

[dev-dependencies]
pretty-hex = "0.4.1"

[package.metadata.deb]
assets = [
  ["target/release/ods2cascade", "usr/bin/", "755"],
  ["README.md", "usr/share/doc/ods2cascade/", "644"],
  ["doc/manual/build/man/ods2cascade.1", "usr/share/man/man1/", "644"],
]
name = "ods2cascade"
maintainer = "NLnet Labs <cascade@nlnetlabs.nl>"
license-file = ["LICENSE", "0"]
depends = "$auto"
priority = "optional"
changelog = "target/debian/changelog" # this will be generated by the pkg workflow
copyright = "Copyright (c) 2026, NLnet Labs. All rights reserved."

[package.metadata.generate-rpm]
summary = "A command line tool to assist with migration from OpenDNSSEC to Cascade"
assets = [
  { source = "target/release/ods2cascade", dest = "/usr/bin/ods2cascade", mode = "755" },
  { source = "README.md", dest = "/usr/share/doc/ods2cascade/README.md", mode = "644", doc = true },
  { source = "doc/manual/build/man/ods2cascade.1", dest = "/usr/share/man/man1/ods2cascade.1", mode = "644", doc = true },
]
