[package]
name = "ods2cascade"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[dependencies]
anyhow            = "1.0.100"
atoi              = "2.0.0"
# TODO: Upgrade our Cascade version in Cargo.lock and Use domain main, as Cascade now uses domain main.
cascade           = { git = "https://github.com/NLnetLabs/cascade" }
domain            = { git = "https://github.com/NLnetLabs/domain", branch = "patches-for-nameshed-prototype" } # Use the same domain as cascade
fs-err            = "3.2.0"
kmip2pkcs11-cfg   = { git = "https://github.com/NLnetLabs/kmip2pkcs11", version = "0.1.0-alpha" }
indoc             = "2.0.7"
pretty_assertions = "1.4.1"
quick-xml         = { version = "0.38.3", features = ["serialize"] }
sanitize-filename = "0.6.0"
serde             = { version = "1.0.228", features = ["derive"] }
sqlx              = { version = "0.8.6", features = ["sqlite", "mysql"] }
tokio             = { version = "1.48.0", features = ["rt", "macros"] }
toml              = "0.9.8"
