[package]
name = "ods2cascade"
version = "0.1.0-alpha1"
edition = "2024"
rust-version = "1.88"

[dependencies]
anyhow            = "1.0.100"
atoi              = "2.0.0"
cascaded          = { git = "https://github.com/NLnetLabs/cascade", branch = "main", default-features = false }
domain            = { git = "https://github.com/NLnetLabs/domain", branch = "main", version = "0.11.1", default-features = false } # Use the same domain as cascade
fs-err            = "3.2.2"
indoc = "2.0.7"
pretty_assertions = "1.4.1"
quick-xml         = { version = "0.38.4", features = ["serialize"] }
sanitize-filename = "0.6.0"
serde             = { version = "1.0.228", features = ["derive"] }
sqlx              = { version = "0.8.6", features = ["sqlite", "mysql"] }
tokio             = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
toml              = "0.9.11"
