version = "v1"

[daemon]
log-level = "warning"
daemonize = true
identity = "root:root"

[daemon.log-target]
type = "syslog"

[pkcs11]
lib-path = "/path/to/some/pkcs11/module.so"

[server]
addr = "127.0.0.1:5696"
