lib_path = "/path/to/some/pkcs11/module.so"
user = "some-user" # Based on <Signer><Privileges><User> from OpenDNSSEC configuration file conf.xml
group = "some-group" # Based on <Signer><Privileges><Group> from OpenDNSSEC configuration file conf.xml
